### ISSUE TITLE
Defining multiple stories breaks UI rendering

### ISSUE THREAD

**Issue by DevHusariaSolutions** [elite174/storybook-solid-js#4]
![image](https://user-images.githubusercontent.com/89352849/232533904-4ddc5284-221e-476d-bfcb-e722ad922ac3.png)

If we expand Your example by:

```ts
export const Second: Story = {
  args: {
    initialValue: 35,
  },
};
```

Then we see, that only LAST story renders.
It happened in our private repository, no matter how eazy or advanced component is.

If we click something on Storybook controls - it will render in missing place of default story view, but not at first render.

**Comment by elite174** [comment]
@DevHusariaSolutions Thank you for reporting this!
I discovered that the issue was because of `disposeStory` fn:

![image](https://user-images.githubusercontent.com/13636224/232622799-9d34eb0b-f55b-45b3-9e97-5ef92efb2080.png)

Each time storybook renders a new story the dispose function was called and it caused disposing the previous story. So only the last story rendered.

To fix this you need to update `preview.js` file with the code below (get rid of dispose).

```ts
export const decorators = [
  (Story) => {
    const solidRoot = document.createElement("div");

    render(Story, solidRoot);

    return solidRoot;
  },
];
```
I've already updated the repo.

**Comment by elite174** [comment]
The weird thing I discovered is that Storybook for some reason renders this `render` function twice. One time inside the decorator above (OK), and another time somewhere else without this decorator (NOT OK).

![image](https://user-images.githubusercontent.com/13636224/232623293-a3c96ca4-4866-4159-bdd1-1245d2874592.png)

That's why solid complains about second render:

![image](https://user-images.githubusercontent.com/13636224/232623486-fa5a051a-56a5-42a4-a215-9f2dc0717135.png)

My guess is that storybook uses react and strict mode in which it renders everything twice. I still need to figure this out.

**Comment by elite174** [comment]
The issue with rerendering disappeared in the latest storybook version :)
